"""add village facts tables

Revision ID: 90e5d5c895d5
Revises: b2822ab433e5
Create Date: 2026-06-16 22:36:34.286126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e5d5c895d5'
down_revision: Union[str, Sequence[str], None] = 'b2822ab433e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyv_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyv_villages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_home_village', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyv_village_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('village_id', sa.String(), nullable=False),
    sa.Column('metric_id', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('as_of_date', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['kyv_metrics.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['kyv_villages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('village_id', 'metric_id', name='uq_one_value_per_village_metric')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyv_village_values')
    op.drop_table('kyv_villages')
    op.drop_table('kyv_metrics')
    # ### end Alembic commands ###
