"""add price history table

Revision ID: d5ff0868b79c
Revises: 90e5d5c895d5
Create Date: 2026-06-17 23:54:43.140096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ff0868b79c'
down_revision: Union[str, Sequence[str], None] = '90e5d5c895d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_item_id'), 'price_history', ['item_id'], unique=False)
    op.create_index('ix_price_history_item_mode_time', 'price_history', ['item_id', 'mode', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_price_history_mode'), 'price_history', ['mode'], unique=False)
    op.create_index(op.f('ix_price_history_vendor_id'), 'price_history', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_vendor_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_mode'), table_name='price_history')
    op.drop_index('ix_price_history_item_mode_time', table_name='price_history')
    op.drop_index(op.f('ix_price_history_item_id'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
