"""add youtube_link to promises

Revision ID: e2b575fe146a
Revises: a7c19f4e2b03
Create Date: 2026-06-13 11:46:30.627736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b575fe146a'
down_revision: Union[str, Sequence[str], None] = 'a7c19f4e2b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promises', sa.Column('youtube_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promises', 'youtube_link')
    # ### end Alembic commands ###
